@baseUrl = http://localhost:3000/api

### REGISTER
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
  "username": "ddddddd",
  "email": "test@test.com",
  "password": "123456789"
}

### LOGIN
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "123456"
}

### REFRESH
POST {{baseUrl}}/auth/refresh
Content-Type: application/json

### LOGOUT
POST {{baseUrl}}/auth/logout
Content-Type: application/json