### =========================
### USERS API TESTS
### =========================
@baseUrl = http://localhost:3000/api

---

### =========================
### GET USER BY ID
### =========================
GET {{baseUrl}}/users/{userId}

---

### =========================
### DISABLE USER
### =========================
PATCH {{baseUrl}}/users/{userId}/disable
Content-Type: application/json

---

### =========================
### GET USER BY EMAIL (if exposed for debug)
### =========================
GET {{baseUrl}}/users/email/test@test.com